package com.sp.locations;

public class GoogleResultStrings {

	static final String FIFTY_1_ZERO = "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" +
			"<GeocodeResponse>" +
			"<status>OK</status>" +
			"<result>" +
			"<type>route</type>" +
			"<formatted_address>A275, Uckfield, East Sussex TN22 3QU, UK</formatted_address>" +
			"<address_component>" +
			"<long_name>A275</long_name>" +
			"<short_name>A275</short_name>" +
			"<type>route</type>" +
			"</address_component>" +
			"<address_component>" +
			"<long_name>East Sussex</long_name>" +
			"<short_name>East Susx</short_name>" +
			"<type>administrative_area_level_2</type>" +
			"<type>political</type>" +
			"</address_component>" +
			"<address_component>" +
			"<long_name>United Kingdom</long_name>" +
			"<short_name>GB</short_name>" +
			"<type>country</type>" +
			"<type>political</type>" +
			"</address_component>" +
			"<address_component>" +
			"<long_name>TN22 3QU</long_name>" +
			"<short_name>TN22 3QU</short_name>" +
			"<type>postal_code</type>" +
			"</address_component>" +
			"<address_component>" +
			"<long_name>Uckfield</long_name>" +
			"<short_name>Uckfield</short_name>" +
			"<type>postal_town</type>" +
			"</address_component>" +
			"<geometry>" +
			"<location>" +
			"<lat>50.9970080</lat>" +
			"<lng>0.0048768</lng>" +
			"</location>" +
			"<location_type>APPROXIMATE</location_type>" +
			"<viewport>" +
			"<southwest>" +
			"<lat>50.9950345</lat>" +
			"<lng>0.0020615</lng>" +
			"</southwest>" +
			"<northeast>" +
			"<lat>50.9994328</lat>" +
			"<lng>0.0060608</lng>" +
			"</northeast>" +
			"</viewport>" +
			"<bounds>" +
			"<southwest>" +
			"<lat>50.9950345</lat>" +
			"<lng>0.0020615</lng>" +
			"</southwest>" +
			"<northeast>" +
			"<lat>50.9994328</lat>" +
			"<lng>0.0060608</lng>" +
			"</northeast>" +
			"</bounds>" +
			"</geometry>" +
			"</result>" +
			"<result>" +
			"<type>postal_code</type>" +
			"<formatted_address>Uckfield TN22 3QH, UK</formatted_address>" +
			"<address_component>" +
			"<long_name>TN22 3QH</long_name>" +
			"<short_name>TN22 3QH</short_name>" +
			"<type>postal_code</type>" +
			"</address_component>" +
			"<address_component>" +
			"<long_name>Uckfield</long_name>" +
			"<short_name>Uckfield</short_name>" +
			"<type>locality</type>" +
			"<type>political</type>" +
			"</address_component>" +
			"<address_component>" +
			"<long_name>United Kingdom</long_name>" +
			"<short_name>GB</short_name>" +
			"<type>country</type>" +
			"<type>political</type>" +
			"</address_component>" +
			"<geometry>" +
			"<location>" +
			"<lat>50.9964728</lat>" +
			"<lng>-0.0036837</lng>" +
			"</location>" +
			"<location_type>APPROXIMATE</location_type>" +
			"<viewport>" +
			"<southwest>" +
			"<lat>50.9928693</lat>" +
			"<lng>-0.0192871</lng>" +
			"</southwest>" +
			"<northeast>" +
			"<lat>51.0012712</lat>" +
			"<lng>0.0007928</lng>" +
			"</northeast>" +
			"</viewport>" +
			"<bounds>" +
			"<southwest>" +
			"<lat>50.9928693</lat>" +
			"<lng>-0.0192871</lng>" +
			"</southwest>" +
			"<northeast>" +
			"<lat>51.0012712</lat>" +
			"<lng>0.0007928</lng>" +
			"</northeast>" +
			"</bounds>" +
			"</geometry>" +
			"</result>" +
			"<result>" +
			"<type>administrative_area_level_4</type>" +
			"<type>political</type>" +
			"<formatted_address>Fletching, East Sussex, UK</formatted_address>" +
			"<address_component>" +
			"<long_name>Fletching</long_name>" +
			"<short_name>Fletching</short_name>" +
			"<type>administrative_area_level_4</type>" +
			"<type>political</type>" +
			"</address_component>" +
			"<address_component>" +
			"<long_name>Wealden District</long_name>" +
			"<short_name>Wealden District</short_name>" +
			"<type>administrative_area_level_3</type>" +
			"<type>political</type>" +
			"</address_component>" +
			"<address_component>" +
			"<long_name>East Sussex</long_name>" +
			"<short_name>East Susx</short_name>" +
			"<type>administrative_area_level_2</type>" +
			"<type>political</type>" +
			"</address_component>" +
			"<address_component>" +
			"<long_name>England</long_name>" +
			"<short_name>England</short_name>" +
			"<type>administrative_area_level_1</type>" +
			"<type>political</type>" +
			"</address_component>" +
			"<address_component>" +
			"<long_name>United Kingdom</long_name>" +
			"<short_name>GB</short_name>" +
			"<type>country</type>" +
			"<type>political</type>" +
			"</address_component>" +
			"<geometry>" +
			"<location>" +
			"<lat>51.0018897</lat>" +
			"<lng>0.0345630</lng>" +
			"</location>" +
			"<location_type>APPROXIMATE</location_type>" +
			"<viewport>" +
			"<southwest>" +
			"<lat>50.9642515</lat>" +
			"<lng>-0.0201226</lng>" +
			"</southwest>" +
			"<northeast>" +
			"<lat>51.0285530</lat>" +
			"<lng>0.0821536</lng>" +
			"</northeast>" +
			"</viewport>" +
			"<bounds>" +
			"<southwest>" +
			"<lat>50.9642515</lat>" +
			"<lng>-0.0201226</lng>" +
			"</southwest>" +
			"<northeast>" +
			"<lat>51.0285530</lat>" +
			"<lng>0.0821536</lng>" +
			"</northeast>" +
			"</bounds>" +
			"</geometry>" +
			"</result>" +
			"<result>" +
			"<type>postal_code_prefix</type>" +
			"<type>postal_code</type>" +
			"<formatted_address>TN22, UK</formatted_address>" +
			"<address_component>" +
			"<long_name>TN22</long_name>" +
			"<short_name>TN22</short_name>" +
			"<type>postal_code_prefix</type>" +
			"<type>postal_code</type>" +
			"</address_component>" +
			"<address_component>" +
			"<long_name>United Kingdom</long_name>" +
			"<short_name>GB</short_name>" +
			"<type>country</type>" +
			"<type>political</type>" +
			"</address_component>" +
			"<geometry>" +
			"<location>" +
			"<lat>50.9914087</lat>" +
			"<lng>0.1152655</lng>" +
			"</location>" +
			"<location_type>APPROXIMATE</location_type>" +
			"<viewport>" +
			"<southwest>" +
			"<lat>50.9195267</lat>" +
			"<lng>-0.0192871</lng>" +
			"</southwest>" +
			"<northeast>" +
			"<lat>51.0727409</lat>" +
			"<lng>0.2206206</lng>" +
			"</northeast>" +
			"</viewport>" +
			"<bounds>" +
			"<southwest>" +
			"<lat>50.9195267</lat>" +
			"<lng>-0.0192871</lng>" +
			"</southwest>" +
			"<northeast>" +
			"<lat>51.0727409</lat>" +
			"<lng>0.2206206</lng>" +
			"</northeast>" +
			"</bounds>" +
			"</geometry>" +
			"</result>" +
			"<result>" +
			"<type>postal_town</type>" +
			"<formatted_address>Uckfield TN22, UK</formatted_address>" +
			"<address_component>" +
			"<long_name>Uckfield</long_name>" +
			"<short_name>Uckfield</short_name>" +
			"<type>postal_town</type>" +
			"</address_component>" +
			"<address_component>" +
			"<long_name>United Kingdom</long_name>" +
			"<short_name>GB</short_name>" +
			"<type>country</type>" +
			"<type>political</type>" +
			"</address_component>" +
			"<address_component>" +
			"<long_name>TN22</long_name>" +
			"<short_name>TN22</short_name>" +
			"<type>postal_code_prefix</type>" +
			"<type>postal_code</type>" +
			"</address_component>" +
			"<geometry>" +
			"<location>" +
			"<lat>50.9914087</lat>" +
			"<lng>0.1152655</lng>" +
			"</location>" +
			"<location_type>APPROXIMATE</location_type>" +
			"<viewport>" +
			"<southwest>" +
			"<lat>50.9195267</lat>" +
			"<lng>-0.0192871</lng>" +
			"</southwest>" +
			"<northeast>" +
			"<lat>51.0727409</lat>" +
			"<lng>0.2206206</lng>" +
			"</northeast>" +
			"</viewport>" +
			"<bounds>" +
			"<southwest>" +
			"<lat>50.9195267</lat>" +
			"<lng>-0.0192871</lng>" +
			"</southwest>" +
			"<northeast>" +
			"<lat>51.0727409</lat>" +
			"<lng>0.2206206</lng>" +
			"</northeast>" +
			"</bounds>" +
			"</geometry>" +
			"</result>" +
			"<result>" +
			"<type>administrative_area_level_3</type>" +
			"<type>political</type>" +
			"<formatted_address>Wealden District, East Sussex, UK</formatted_address>" +
			"<address_component>" +
			"<long_name>Wealden District</long_name>" +
			"<short_name>Wealden District</short_name>" +
			"<type>administrative_area_level_3</type>" +
			"<type>political</type>" +
			"</address_component>" +
			"<address_component>" +
			"<long_name>East Sussex</long_name>" +
			"<short_name>East Susx</short_name>" +
			"<type>administrative_area_level_2</type>" +
			"<type>political</type>" +
			"</address_component>" +
			"<address_component>" +
			"<long_name>England</long_name>" +
			"<short_name>England</short_name>" +
			"<type>administrative_area_level_1</type>" +
			"<type>political</type>" +
			"</address_component>" +
			"<address_component>" +
			"<long_name>United Kingdom</long_name>" +
			"<short_name>GB</short_name>" +
			"<type>country</type>" +
			"<type>political</type>" +
			"</address_component>" +
			"<geometry>" +
			"<location>" +
			"<lat>50.9703846</lat>" +
			"<lng>0.2306394</lng>" +
			"</location>" +
			"<location_type>APPROXIMATE</location_type>" +
			"<viewport>" +
			"<southwest>" +
			"<lat>50.7369527</lat>" +
			"<lng>-0.0362407</lng>" +
			"</southwest>" +
			"<northeast>" +
			"<lat>51.1474020</lat>" +
			"<lng>0.4501300</lng>" +
			"</northeast>" +
			"</viewport>" +
			"<bounds>" +
			"<southwest>" +
			"<lat>50.7369527</lat>" +
			"<lng>-0.0362407</lng>" +
			"</southwest>" +
			"<northeast>" +
			"<lat>51.1474020</lat>" +
			"<lng>0.4501300</lng>" +
			"</northeast>" +
			"</bounds>" +
			"</geometry>" +
			"</result>" +
			"<result>" +
			"<type>administrative_area_level_2</type>" +
			"<type>political</type>" +
			"<formatted_address>East Sussex, UK</formatted_address>" +
			"<address_component>" +
			"<long_name>East Sussex</long_name>" +
			"<short_name>East Susx</short_name>" +
			"<type>administrative_area_level_2</type>" +
			"<type>political</type>" +
			"</address_component>" +
			"<address_component>" +
			"<long_name>England</long_name>" +
			"<short_name>England</short_name>" +
			"<type>administrative_area_level_1</type>" +
			"<type>political</type>" +
			"</address_component>" +
			"<address_component>" +
			"<long_name>United Kingdom</long_name>" +
			"<short_name>GB</short_name>" +
			"<type>country</type>" +
			"<type>political</type>" +
			"</address_component>" +
			"<geometry>" +
			"<location>" +
			"<lat>50.9285982</lat>" +
			"<lng>0.2764899</lng>" +
			"</location>" +
			"<location_type>APPROXIMATE</location_type>" +
			"<viewport>" +
			"<southwest>" +
			"<lat>50.7334348</lat>" +
			"<lng>-0.1358669</lng>" +
			"</southwest>" +
			"<northeast>" +
			"<lat>51.1474020</lat>" +
			"<lng>0.8678558</lng>" +
			"</northeast>" +
			"</viewport>" +
			"<bounds>" +
			"<southwest>" +
			"<lat>50.7334348</lat>" +
			"<lng>-0.1358669</lng>" +
			"</southwest>" +
			"<northeast>" +
			"<lat>51.1474020</lat>" +
			"<lng>0.8678558</lng>" +
			"</northeast>" +
			"</bounds>" +
			"</geometry>" +
			"</result>" +
			"<result>" +
			"<type>administrative_area_level_1</type>" +
			"<type>political</type>" +
			"<formatted_address>England, UK</formatted_address>" +
			"<address_component>" +
			"<long_name>England</long_name>" +
			"<short_name>England</short_name>" +
			"<type>administrative_area_level_1</type>" +
			"<type>political</type>" +
			"</address_component>" +
			"<address_component>" +
			"<long_name>United Kingdom</long_name>" +
			"<short_name>GB</short_name>" +
			"<type>country</type>" +
			"<type>political</type>" +
			"</address_component>" +
			"<geometry>" +
			"<location>" +
			"<lat>52.3555177</lat>" +
			"<lng>-1.1743197</lng>" +
			"</location>" +
			"<location_type>APPROXIMATE</location_type>" +
			"<viewport>" +
			"<southwest>" +
			"<lat>49.9588004</lat>" +
			"<lng>-5.7169817</lng>" +
			"</southwest>" +
			"<northeast>" +
			"<lat>55.8111127</lat>" +
			"<lng>1.7629159</lng>" +
			"</northeast>" +
			"</viewport>" +
			"<bounds>" +
			"<southwest>" +
			"<lat>49.8647517</lat>" +
			"<lng>-6.4177822</lng>" +
			"</southwest>" +
			"<northeast>" +
			"<lat>55.8111127</lat>" +
			"<lng>1.7629159</lng>" +
			"</northeast>" +
			"</bounds>" +
			"</geometry>" +
			"</result>" +
			"<result>" +
			"<type>country</type>" +
			"<type>political</type>" +
			"<formatted_address>United Kingdom</formatted_address>" +
			"<address_component>" +
			"<long_name>United Kingdom</long_name>" +
			"<short_name>GB</short_name>" +
			"<type>country</type>" +
			"<type>political</type>" +
			"</address_component>" +
			"<geometry>" +
			"<location>" +
			"<lat>55.3780510</lat>" +
			"<lng>-3.4359730</lng>" +
			"</location>" +
			"<location_type>APPROXIMATE</location_type>" +
			"<viewport>" +
			"<southwest>" +
			"<lat>49.8669688</lat>" +
			"<lng>-8.6493572</lng>" +
			"</southwest>" +
			"<northeast>" +
			"<lat>60.8565530</lat>" +
			"<lng>1.7627096</lng>" +
			"</northeast>" +
			"</viewport>" +
			"<bounds>" +
			"<southwest>" +
			"<lat>34.5625145</lat>" +
			"<lng>-8.6493572</lng>" +
			"</southwest>" +
			"<northeast>" +
			"<lat>60.9023960</lat>" +
			"<lng>33.9165550</lng>" +
			"</northeast>" +
			"</bounds>" +
			"</geometry>" +
			"</result>" +
			"</GeocodeResponse>";

}