<%@page import="com.shine.boards.NoticeBoard"%>
<%@ page session="false" %>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="sec" uri="http://www.springframework.org/security/tags" %>
<%@ taglib uri="http://www.springframework.org/tags/form" prefix="form"%>
<!DOCTYPE html>
<html>
<head>
<jsp:include page="head/head.jsp"></jsp:include>

</head>
<body>

<div class="greenCall ui-page ui-body-c ui-page-footer-fullscreen ui-page-active" id="controls" data-role="page" style="min-height: 363px;">
  <div data-role="header" class="ui-header ui-bar-a" role="banner">
    <div class="ui-grid-b greenohead">
      <div class="ui-block-a"><a data-transition="slide" title="Logo" class="logo ui-link" href="#menu"><img alt="logo" src="${pageContext.request.contextPath}/mw/static/images/streetpin-logo-glow.png"></a></div>
      <!--images/streetpin-logo-noglow.png-->
      <div class="ui-block-b">
        <div class="tabBtns ui-navbar" data-role="tabs" role="navigation">
        	<a data-theme="b" data-inline="true" data-iconpos="top" data-icon="map" data-role="button" href="#tab-1" data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="span" class="ui-btn ui-btn-up-b ui-btn-inline ui-btn-icon-top"><span class="ui-btn-inner"><span class="ui-btn-text"></span><span class="ui-icon ui-icon-map ui-icon-shadow">&nbsp;</span></span></a>
        	<a data-theme="b" data-inline="true" data-iconpos="top" data-icon="list" data-role="button" href="#tab-2" data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="span" class="ui-btn ui-btn-inline ui-btn-icon-top ui-btn-up-b ui-btn-active"><span class="ui-btn-inner"><span class="ui-btn-text"></span><span class="ui-icon ui-icon-list ui-icon-shadow">&nbsp;</span></span></a> </div>
      </div>
      <div class="ui-block-c">
        <div class="locBtns"> <a data-transition="pop" data-position-to="window" data-rel="popup" data-iconpos="top" data-icon="dicon" data-inline="true" data-theme="b" data-role="button" id="myLoc" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" class="ui-btn ui-btn-up-b ui-shadow ui-btn-corner-all ui-btn-inline ui-btn-icon-top"><span class="ui-btn-inner ui-btn-corner-all"><span class="ui-btn-text"></span><span class="ui-icon ui-icon-dicon ui-icon-shadow">&nbsp;</span></span></a>
          <!--<a data-role="button" data-theme="b" data-inline="true" data-icon="pluss" data-iconpos="top" href="#popupLogin" data-rel="popup" data-position-to="window" data-transition="pop"></a>-->
        </div>
      </div>
    </div>
    <!-- /grid-a -->
    <div class="searchArea">
      <div class="ui-grid-a">
          <div id="divsearch" class="ui-block-a">
		  	<div class="ui-input-search ui-shadow-inset ui-btn-corner-all ui-btn-shadow ui-icon-searchfield ui-body-a"><input type="text" data-type="search" id="txtsearch" placeholder="Find a board" class="ui-input-text ui-body-a"><a title="clear text" class="ui-input-clear ui-btn ui-btn-up-a ui-shadow ui-btn-corner-all ui-fullsize ui-btn-icon-notext ui-input-clear-hidden" href="#" data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-icon="delete" data-iconpos="notext" data-theme="a" data-mini="false"><span class="ui-btn-inner ui-btn-corner-all"><span class="ui-btn-text">clear text</span><span class="ui-icon ui-icon-delete ui-icon-shadow">&nbsp;</span></span></a></div>
			<div style="display: none;"><!-- placeholder for searchPopup --></div>
		  </div>
          <div class="ui-block-b">
            <div class="greenOnBtn"> <div data-corners="true" data-shadow="true" data-iconshadow="true" data-wrapperels="span" data-icon="" data-iconpos="" data-theme="c" data-mini="true" class="ui-btn ui-btn-up-c ui-shadow ui-btn-corner-all ui-mini" aria-disabled="false"><span class="ui-btn-inner ui-btn-corner-all"><span class="ui-btn-text">Search</span></span><input type="button" data-theme="c" data-mini="true" value="Search" name="boardsearch" id="boardsearch" class="ui-btn-hidden" aria-disabled="false"></div> </div>
          </div>
        </div>
    </div>


  </div>
    <div id="tab-2" class="ui-tabs-content ui-tabs-content-active">
      <ul id="listboard" class="listView ui-listview" data-role="listview">
      
	      <c:forEach items="${boards}" var="board">
	      	<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb ui-btn-up-c">
	      	<div class="ui-btn-inner ui-li"><div class="ui-btn-text">
	      	<a data-transition="slide" href="${pageContext.request.contextPath}/mw/board?id=<c:out value="${board.id}"/> " class="ui-link-inherit"><img alt="image1" src="${pageContext.request.contextPath}/static/images/cat-streetpin-noborder.png" class="ui-li-thumb"/><h3 class="ui-li-heading"><c:out value="${board.locationName}"/></h3><p class="ui-li-desc">156 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
		  </c:forEach>

<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb ui-btn-up-c"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=385" class="ui-link-inherit"><img alt="image1" src="images/cat-restaurant-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Thursday Food Market</h3><p class="ui-li-desc">645 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb ui-btn-up-c"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=358" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">My office: Starbucks/Cafe Nero</h3><p class="ui-li-desc">1028 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb ui-btn-up-c"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=357" class="ui-link-inherit"><img alt="image1" src="images/cat-events-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">F&amp;L </h3><p class="ui-li-desc">1243 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb ui-btn-up-c"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=387" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">James</h3><p class="ui-li-desc">1425 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb ui-btn-up-c"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=386" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Anujas board</h3><p class="ui-li-desc">1660 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb ui-btn-up-c"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=353" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">HELO Project</h3><p class="ui-li-desc">1718 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb ui-btn-up-c"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=380" class="ui-link-inherit"><img alt="image1" src="images/cat-social-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Innovation Warehouse</h3><p class="ui-li-desc">2158 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb ui-btn-up-c"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=404" class="ui-link-inherit"><img alt="image1" src="images/cat-place-interest-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">BT Centre</h3><p class="ui-li-desc">2244 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb ui-btn-up-c"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=345" class="ui-link-inherit"><img alt="image1" src="images/cat-station-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Euston Station</h3><p class="ui-li-desc">2363 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=378" class="ui-link-inherit"><img alt="image1" src="images/cat-station-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Liverpool Street Station</h3><p class="ui-li-desc">3254 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb ui-btn-up-c"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=351" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Google Campus</h3><p class="ui-li-desc">3375 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=376" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">RBS Bishopsgate</h3><p class="ui-li-desc">3689 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=379" class="ui-link-inherit"><img alt="image1" src="images/cat-station-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Shoreditch High St Station</h3><p class="ui-li-desc">3937 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb ui-btn-up-c"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=372" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Copthorne Tara</h3><p class="ui-li-desc">4468 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb ui-btn-up-c"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=395" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">STA Travel Kensington</h3><p class="ui-li-desc">4542 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb ui-btn-up-c"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=338" class="ui-link-inherit"><img alt="image1" src="images/cat-station-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">High Street Kensington Station</h3><p class="ui-li-desc">4551 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=382" class="ui-link-inherit"><img alt="image1" src="images/cat-sport-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Club Kensington</h3><p class="ui-li-desc">4828 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=352" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">hello</h3><p class="ui-li-desc">4923 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=356" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">The Boys House</h3><p class="ui-li-desc">5023 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb ui-btn-up-c"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=355" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">The Lavender Social Board</h3><p class="ui-li-desc">5150 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb ui-btn-up-c"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=388" class="ui-link-inherit"><img alt="image1" src="images/cat-place-interest-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">millfields</h3><p class="ui-li-desc">8240 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=403" class="ui-link-inherit"><img alt="image1" src="images/cat-place-interest-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Catford - The Island</h3><p class="ui-li-desc">10250 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb ui-btn-up-c"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=373" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Crystal Palace dinosaur park</h3><p class="ui-li-desc">10767 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=392" class="ui-link-inherit"><img alt="image1" src="images/cat-place-interest-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Arts Depot</h3><p class="ui-li-desc">12228 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb ui-btn-up-c"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=390" class="ui-link-inherit"><img alt="image1" src="images/cat-restaurant-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">High Street</h3><p class="ui-li-desc">12475 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb ui-btn-up-c"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=389" class="ui-link-inherit"><img alt="image1" src="images/cat-social-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Childrens Play Group</h3><p class="ui-li-desc">12635 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=393" class="ui-link-inherit"><img alt="image1" src="images/cat-sport-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Golf</h3><p class="ui-li-desc">13034 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=391" class="ui-link-inherit"><img alt="image1" src="images/cat-place-interest-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Dollis Way</h3><p class="ui-li-desc">13377 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=410" class="ui-link-inherit"><img alt="image1" src="images/cat-restaurant-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Gesti's</h3><p class="ui-li-desc">21369 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb ui-btn-up-c"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=377" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Angelo's Barbers</h3><p class="ui-li-desc">21459 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb ui-btn-up-c"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=347" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Andy's bored</h3><p class="ui-li-desc">21841 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=365" class="ui-link-inherit"><img alt="image1" src="images/cat-sport-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Orpington Road Runners</h3><p class="ui-li-desc">22227 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=405" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Farnborough by pass</h3><p class="ui-li-desc">22570 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=383" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Woods</h3><p class="ui-li-desc">22650 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=375" class="ui-link-inherit"><img alt="image1" src="images/cat-place-interest-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Tim's board</h3><p class="ui-li-desc">22681 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=346" class="ui-link-inherit"><img alt="image1" src="images/cat-social-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Queen's Head</h3><p class="ui-li-desc">22855 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=344" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Old Hill playground</h3><p class="ui-li-desc">22949 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=398" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Rec</h3><p class="ui-li-desc">23010 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=384" class="ui-link-inherit"><img alt="image1" src="images/cat-restaurant-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">artichoke</h3><p class="ui-li-desc">27548 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=342" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Spencers Wood Library</h3><p class="ui-li-desc">59974 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=349" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Jamie's Brighton</h3><p class="ui-li-desc">76341 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=332" class="ui-link-inherit"><img alt="image1" src="images/cat-education-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Norwich Campus</h3><p class="ui-li-desc">160353 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=362" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Birmingham City University </h3><p class="ui-li-desc">165226 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=337" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Lawrence </h3><p class="ui-li-desc">174148 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=381" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Reflow Studio</h3><p class="ui-li-desc">226982 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=350" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">77jch</h3><p class="ui-li-desc">300644 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=397" class="ui-link-inherit"><img alt="image1" src="images/cat-pub-bar-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Millbank Arms</h3><p class="ui-li-desc">318669 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=348" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Fidelito</h3><p class="ui-li-desc">324792 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=364" class="ui-link-inherit"><img alt="image1" src="images/cat-place-interest-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Duchess of Duke Street</h3><p class="ui-li-desc">554178 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=333" class="ui-link-inherit"><img alt="image1" src="images/cat-station-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Argyle St Station</h3><p class="ui-li-desc">554521 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>
<li data-corners="false" data-shadow="false" data-iconshadow="true" data-wrapperels="div" data-icon="arrow-r" data-iconpos="right" data-theme="c" class="ui-btn ui-btn-up-c ui-btn-icon-right ui-li-has-arrow ui-li ui-li-has-thumb ui-li-last"><div class="ui-btn-inner ui-li"><div class="ui-btn-text"><a data-transition="slide" href="#boardscreen?id=343" class="ui-link-inherit"><img alt="image1" src="images/cat-streetpin-noborder.png" class="ui-li-thumb"><h3 class="ui-li-heading">Glasgow Central</h3><p class="ui-li-desc">555001 m</p> </a></div><span class="ui-icon ui-icon-arrow-r ui-icon-shadow">&nbsp;</span></div></li>


</ul>
    </div>
  </div>
<div class="ui-screen-hidden ui-popup-screen fade" id="searchPopup-screen"></div><div class="ui-popup-container ui-selectmenu-hidden" id="searchPopup-popup"><div class="ui-corner-all ui-popup ui-body-a ui-overlay-shadow" data-tolerance="5,90" data-theme="a" id="searchPopup" data-role="popup" aria-disabled="false" data-disabled="false" data-shadow="true" data-corners="true" data-transition="none" data-position-to="origin">
				<ul class="loc-list ui-listview ui-listview-inset ui-corner-all ui-shadow" data-theme="a" style="max-width:310px;" data-inset="true" data-role="listview" id="searchpoplist"></ul>
			</div></div><div class="ui-popup-screen fade ui-screen-hidden" id="popupLogin-screen"></div><div class="ui-popup-container ui-selectmenu-hidden" id="popupLogin-popup"><div class="ui-corner-all ui-popup ui-body-a ui-overlay-shadow" data-theme="a" id="popupLogin" data-role="popup" aria-disabled="false" data-disabled="false" data-shadow="true" data-corners="true" data-transition="none" data-position-to="origin">
        <div class="popup-inner">
          <h3>What's next?</h3>
          <div class="greenOnBtn"> <a data-rel="back" class="dashBtn" data-role="none" href="#">Find a board</a></div><!-- onClick="closePopup();"-->
          <div class="greenOnBtn"><a data-transition="slide" class="dashBtn" data-role="none" href="#landgrab">Create &amp; claim your board</a></div>
          <div class="greenOnBtn"><a data-transition="slide" class="dashBtn" data-role="none" href="#howto">How to...</a></div>
          <div class="greenOnBtn"><a data-rel="back" class="redBtn" data-role="none" href="#">Close menu</a></div><!-- onClick="closePopup();"-->
          <p>
            <input type="checkbox" onclick="setPopup();" data-role="none" id="popupshow" name="popupshow">
            <label for="popupshow">Don’t show this box again?</label>
          </p>
        </div>
      </div>
   </div>
</div>

<jsp:include page="head/analytics.html"></jsp:include>
</body>
</html>

